### ISSUE TITLE
latest version entity_picture of the symbol lead to 404 error

### ISSUE THREAD

**Issue by Pirol62** [Danielhiversen/home_assistant_weather_data#17]
Entity in HA
![image](https://user-images.githubusercontent.com/48820003/109817013-b19c8a00-7c31-11eb-993e-f5ed62e52535.png)
obviously the version numer is not correct. The link has another logic as I understood from this link:
https://api.met.no/weatherapi/weathericon/2.0/?symbol=clearsky_night;content_type=image/png 

Result when copy the link out of the entity to chrome
The entity_picture link provides this;
![image](https://user-images.githubusercontent.com/48820003/109816864-85810900-7c31-11eb-8ba2-11826a770ce6.png)

**Comment by jeppper** [comment]
any solution on this?

**Comment by jeppper** [comment]
Should it not be possible to integrate the new weathericon service 2.0 in the sensor.py file and use the downloaded icons?

**Comment by Danielhiversen** [comment]
Yes, it is possible, but someone has to do it :)

**Comment by jeppper** [comment]
Yes I know :-) 
Unfortuneately I have no experience with altering the sensor.file to make it work. 
I DID change the locationforecast to 2.0 and MSL to altirude to make it work for now but I guess it is not enough just to change weathericon from 1.1 to 2.0

**Comment by jeppper** [comment]
Is it possible to change the icon part of the .py file to use local icons instead, now it is no more possible to grab them online.

    @property
    def entity_picture(self):
        """Weather symbol if type is symbol."""
        if self.type != "symbol":
            return None
        return (
            "https://api.met.no/weatherapi/weathericon/2.0/"
            "?symbol={0};content_type=image/png".format(self._state)
        )

**Comment by Pirol62** [comment]
Yes, obviously changing the version number and exchanging the yymbol identifier does not lead to the picture.
I'm not that familiar with python interfaces to find out a solution but they mentioned this component:
https://github.com/nrkno/yr-weather-symbols 
This might be the approach in order to get the pictures.

**Comment by jeppper** [comment]
I guess it is no more possible to call the icons on demand but only to have them locally installed.
How to link the weather ID to an local icon however, I don´t know

**Comment by Pirol62** [comment]
Does anybody has an approach how to translate the code into a picture so far?

**Comment by Olen** [comment]
I just had  a quick look at the new api, and there is no easy way to do this right.  The easy way is to simply download the tgz of icons, and put them somewhere local (`www/images/weather_icons/` or whatever) and then use that path in the integration.
But that would be a manual process for everyone.
The right way would be to be able to access the images either from the web, which requires that someone will host them, or directly from the custom component folder, but I don't think that is possible.
I am not sure what other integrations do, to add images to their packages.  I saw one that had a rather ugly script that copies the files to a path under `www/` on startup, but that does not feel right, although it might be the best solution for now.

**Comment by jeppper** [comment]
I have downloaded the tgz and have put them into www.
Could you maybe show how and where to make changes in the sensor.py file if I would use the local icon files depending on the weather ID. I guess something in the code below has to be changed and some sort of template has to be used.

```
    def entity_picture(self):
        """Weather symbol if type is symbol."""
        if self.type != "symbol":
            return None
        return (
            "https://api.met.no/weatherapi/weathericon/2.0/"
            "?symbol={0};content_type=image/png".format(self._state)
        )
```

**Comment by Pirol62** [comment]
I use a custom button card and wrote this:
`````
entity: sensor.yr_symbol
label: jetzt
layout: vertical
show_entity_picture: true
show_icon: false
show_label: true
show_name: false
show_state: false
show_units: false
size: 40px
styles:
  card:
    - height: 60px
  label:
    - font-size: 12px
state:
  - entity_picture: /local/weather_icons/01d.svg
    label: klar
    value: clearsky_day
  - entity_picture: /local/weather_icons/01n.svg
    label: klar
    value: clearsky_night
  - entity_picture: /local/weather_icons/02d.svg
    label: leicht bewölkt
    value: fair_day
  - entity_picture: /local/weather_icons/02n.svg
    label: leicht bewölkt
    value: fair_night
  - entity_picture: /local/weather_icons/03n.svg
    label: bewölkt
    value: partlycloudy_night
  - entity_picture: /local/weather_icons/03d.svg
    label: bewölkt
    value: partlycloudy_day
  - entity_picture: /local/weather_icons/04.svg
    label: bedeckt
    value: cloudy
  - entity_picture: /local/weather_icons/40d.svg
    label: leichte Regenschauer
    value: lightrainshowers_day
  - entity_picture: /local/weather_icons/40n.svg
    label: leichte Regenschauer
    value: lightrainshowers_night
  - entity_picture: /local/weather_icons/05d.svg
    label: Regenschauer
    value: rainshowers_day
  - entity_picture: /local/weather_icons/05n.svg
    label: Regenschauer
    value: rainshowers_night
  - entity_picture: /local/weather_icons/41d.svg
    label: Starke Regenschauer
    value: heavyrainshowers_day
  - entity_picture: /local/weather_icons/41n.svg
    label: Starke Regenschauer
    value: heavyrainshowers_night
  - entity_picture: /local/weather_icons/06d.svg
    label: Regen und Gewitter
    value: rainshowersandthunder_day
  - entity_picture: /local/weather_icons/06n.svg
    label: Regen und Gewitter
    value: rainshowersandthunder_night
  - entity_picture: /local/weather_icons/25d.svg
    label: Regen und Gewitter
    value: heavyrainshowersandthunder_day
  - entity_picture: /local/weather_icons/25n.svg
    label: Regen und Gewitter
    value: heavyrainshowersandthunder_night
  - entity_picture: /local/weather_icons/07d.svg
    label: Schneeregenschauer
    value: sleetshowers_day
  - entity_picture: /local/weather_icons/07n.svg
    label: Hagelschauer
    value: sleetshowers_night
  - entity_picture: /local/weather_icons/09.svg
    label: Regen
    value: rain
  - entity_picture: /local/weather_icons/10.svg
    label: Starkegen
    value: heavyrain
  - entity_picture: /local/weather_icons/11.svg
    label: Starkregen und Gewitter
    value: heavyrainandthunder
  - entity_picture: /local/weather_icons/12.svg
    label: Hagel
    value: sleet
  - entity_picture: /local/weather_icons/48.svg
    label: Starker Hagel
    value: heavysleet
  - entity_picture: /local/weather_icons/13.svg
    label: Schnee
    value: snow
  - entity_picture: /local/weather_icons/21.svg
    label: Schneeschauer und Gewitter
    value: snowshowersandthunder
  - entity_picture: /local/weather_icons/14.svg
    label: Schnee und Gewitter
    value: snowandthunder
  - entity_picture: /local/weather_icons/15.svg
    label: Nebel
    value: fog
  - entity_picture: /local/weather_icons/30.svg
    label: Regen und Gewitter
    value: lightrainandthunder
  - entity_picture: /local/weather_icons/22.svg
    label: Regen und Gewitter
    value: rainandthunder
  - entity_picture: /local/weather_icons/11.svg
    label: Starkegen und Gewitter
    value: heavyrainandthunder
  - entity_picture: /local/weather_icons/34.svg
    label: Starkschnee und Gewitter
    value: heavysnowandthunder
  - entity_picture: /local/weather_icons/26.svg
    label: Schneeregen Schauer
    value: sleetshowersandthunder
  - entity_picture: /local/weather_icons/43.svg
    label: Starke Schneeregen Schauer
    value: heavysleetshowers
  - entity_picture: /local/weather_icons/45d.svg
    label: Starke Schneeregen Schauer
    value: heavysnowshowers_day
  - entity_picture: /local/weather_icons/45n.svg
    label: Starke Schneeregen Schauer
    value: heavysnowshowers_night
  - entity_picture: /local/weather_icons/31.svg
    label: Leichter Schneeregen und Gewitter
    value: lightsleetandthunder
  - entity_picture: /local/weather_icons/32.svg
    label: Starker Hagel und Gewitter
    value: heavysleetandthunder
  - entity_picture: /local/weather_icons/46.svg
    label: leichter Regen
    value: lightrain
  - entity_picture: /local/weather_icons/47.svg
    label: Schneeregen
    value: lightsleet
  - entity_picture: /local/weather_icons/48.svg
    label: starker Schneeregen
    value: heavysleet
  - entity_picture: /local/weather_icons/49.svg
    label: leichter Schnee
    value: lightsnow
  - entity_picture: /local/weather_icons/33.svg
    label: leichter Schnee
    value: lightsnowandthunder
  - entity_picture: /local/weather_icons/50.svg
    label: Starker Schneefall
    value: heavysnow
tap_action:
  action: null
type: 'custom:button-card'
````
not very elegant but it works
now I try to find out, to use this as template.
I read that it is possible to create templates

**Comment by Pirol62** [comment]
Yeees...works
You can define it as template in the lovelace root

````
button_card_templates:
  weather_button:
    state:
      - entity_picture: /local/weather_icons/01d.svg
        label: klar
        value: clearsky_day
      - entity_picture: /local/weather_icons/01n.svg
        label: klar
        value: clearsky_night
      - entity_picture: /local/weather_icons/02d.svg
        label: leicht bewölkt
        value: fair_day
      - entity_picture: /local/weather_icons/02n.svg
        label: leicht bewölkt
        value: fair_night
      - entity_picture: /local/weather_icons/03n.svg
        label: bewölkt
        .....etc.
````
the set the template:
````
entity: sensor.yr_symbol
template: weather_button
label: jetzt
layout: vertical
````
