### ISSUE TITLE
yr perscipitation state = 0.0 when yr.no reports rain and it's pouring outside.

### ISSUE THREAD

**Issue by palengh** [Danielhiversen/home_assistant_weather_data#25]
Hi, there, Daniel!

I love your work here and at Tibber, so kudos for all your work.
I am running your weather_data integration in HA, integrated using HACS.

I use the percipitation sensor to determine if rain is expected as part of the trigger conditions for my garden watering system. I notice that, even when yr.no is reporting 0,5 mm precipitation (first image), the precipitation sensor in HA reports 0.0.
You have any advice on this?

<img width="1215" alt="Skjermbilde 2021-07-01 kl  20 55 29" src="https://user-images.githubusercontent.com/12332161/124176875-cd188400-daaf-11eb-89c9-ffb352a67ac2.png">

Here is a snapshot of my definitions. Other sensors like wind speed, pressure, temperature, symbol etc. shows just fine. 
```
sensor:
  - platform: weather_data     # home 2h
    name: YrNext2Hours
    forecast: 2
    monitored_conditions:
      - precipitation
      - symbol
  - platform: weather_data     # home now
    name: YrCurrent
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
```

<img width="951" alt="Skjermbilde 2021-07-01 kl  20 56 15" src="https://user-images.githubusercontent.com/12332161/124176912-dace0980-daaf-11eb-9381-61fdd24c1599.png">
