### ISSUE TITLE
- platform: weather_data or just platform: weather ?

### ISSUE THREAD

**Issue by palengh** [Danielhiversen/home_assistant_weather_data#3]
In your readme file you mention replacing `platform: yr` with `platform weather_data`, while the the examples you only refer to `platform: weather_data`.

What is correct?

**Comment by Olen** [comment]
`platform: weather_data` works here.

I think the README is wrong.

**Comment by Danielhiversen** [comment]
It should be

```yaml
# Example configuration.yaml entry
sensor:
  - platform: weather_data
```
