### ISSUE TITLE
Sorry to bother you guys, but I cannot get this to play

### ISSUE THREAD

**Issue by palengh** [Danielhiversen/home_assistant_weather_data#5]
My log shows: 
`2020-09-21 17:13:52 ERROR (MainThread) [homeassistant.config] Platform error: sensor - Integration 'weather_data' not found.`

I have re-installed the met.no integration from the UI, and added the sensor to configuration.yaml
```
sensor:
  - platform: weather_data
    name: weather
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
```
The met.no integration only returns _weather.home_
Still there is the error, and still I cannot get any sensors listed like I did using yr...
